"""initial schema

Revision ID: 11bfb0c5ba6e
Revises: 
Create Date: 2026-08-08 03:16:47.133563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bfb0c5ba6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('master_resume_ref', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('role_interests', sa.JSON(), nullable=False),
    sa.Column('remote_preference', sa.String(), nullable=True),
    sa.Column('salary_floor', sa.Float(), nullable=True),
    sa.Column('target_skill_areas', sa.JSON(), nullable=False),
    sa.Column('preferred_locations', sa.JSON(), nullable=False),
    sa.Column('do_not_apply_companies', sa.JSON(), nullable=False),
    sa.Column('auto_apply_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_tailor_resume_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('careers_page_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('funding_stage', sa.String(), nullable=True),
    sa.Column('size_estimate', sa.String(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('engineering_blog_url', sa.String(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_job_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('remote_type', sa.String(), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('salary_period', sa.String(), nullable=True),
    sa.Column('salary_is_estimated', sa.Boolean(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_job_source_source_job_id')
    )
    op.create_table('recruiter_contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('first_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_resume_version_id', sa.String(), nullable=True),
    sa.Column('current_cover_letter_id', sa.String(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('resume_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_master_version_ref', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('diff_summary', sa.String(), nullable=True),
    sa.Column('render_status', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('has_gaps', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('resume_match', sa.Float(), nullable=False),
    sa.Column('skill_area_fit', sa.Float(), nullable=False),
    sa.Column('career_progression_fit', sa.Float(), nullable=False),
    sa.Column('remote_fit', sa.Float(), nullable=False),
    sa.Column('salary_fit', sa.Float(), nullable=False),
    sa.Column('company_quality', sa.Float(), nullable=False),
    sa.Column('narrative', sa.String(), nullable=False),
    sa.Column('scoring_strategy_version', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_status_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cover_letters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('resume_version_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('render_status', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gmail_message_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('linked_company_id', sa.String(), nullable=True),
    sa.Column('linked_application_id', sa.String(), nullable=True),
    sa.Column('draft_reply_id', sa.String(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linked_application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['linked_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_table('resume_gap_flags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resume_version_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('missing_skill_or_requirement', sa.String(), nullable=False),
    sa.Column('suggested_language', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_gap_flags')
    op.drop_table('email_messages')
    op.drop_table('cover_letters')
    op.drop_table('application_status_events')
    op.drop_table('scores')
    op.drop_table('resume_versions')
    op.drop_table('applications')
    op.drop_table('recruiter_contacts')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('candidate_profile')
    # ### end Alembic commands ###
