"""Repository ports, expressed in domain vocabulary.

Only infrastructure implements these (see
backend/src/careeros/infrastructure/persistence/repositories/), but the signatures belong to the domain
layer since they are phrased entirely in domain terms rather than persistence terms.
"""
from __future__ import annotations

from typing import Protocol

from careeros.domain.application.application import Application
from careeros.domain.candidate.candidate_profile import CandidateProfile
from careeros.domain.company.company import Company
from careeros.domain.job.job import Job, JobSource
from careeros.domain.resume.resume_version import CoverLetter, ResumeGapFlag, ResumeVersion
from careeros.domain.scoring.score import Score


class JobRepository(Protocol):
    async def get_by_id(self, job_id: str) -> Job | None: ...
    async def find_by_source(self, source: JobSource, source_job_id: str) -> Job | None: ...
    async def add(self, job: Job) -> None: ...
    async def save(self, job: Job) -> None: ...

    # "Not yet scored" is the scoring backlog. Expressing it as a query rather than an in-memory queue makes
    # the backlog durable across restarts -- see ScoringService.score_pending.
    async def find_unscored(self, limit: int) -> list[Job]: ...
    async def count_unscored(self) -> int: ...


class CompanyRepository(Protocol):
    async def get_by_id(self, company_id: str) -> Company | None: ...
    async def find_by_website(self, website: str) -> Company | None: ...
    async def find_by_normalized_name(self, normalized_name: str) -> Company | None: ...
    async def add(self, company: Company) -> None: ...
    async def save(self, company: Company) -> None: ...


class ApplicationRepository(Protocol):
    async def get_by_id(self, application_id: str) -> Application | None: ...
    async def get_by_job_id(self, job_id: str) -> Application | None: ...
    async def has_ever_applied(self, job_id: str) -> bool: ...
    async def add(self, application: Application) -> None: ...
    async def save(self, application: Application) -> None: ...


class ScoreRepository(Protocol):
    async def get_latest_for_job(self, job_id: str) -> Score | None: ...
    async def add(self, score: Score) -> None: ...


class ResumeRepository(Protocol):
    async def get_resume_version(self, resume_version_id: str) -> ResumeVersion | None: ...
    async def add_resume_version(self, resume_version: ResumeVersion) -> None: ...
    async def save_resume_version(self, resume_version: ResumeVersion) -> None: ...
    async def list_versions_for_job(self, job_id: str) -> list[ResumeVersion]: ...
    async def get_cover_letter(self, cover_letter_id: str) -> CoverLetter | None: ...
    async def add_cover_letter(self, cover_letter: CoverLetter) -> None: ...
    async def add_gap_flag(self, gap_flag: ResumeGapFlag) -> None: ...
    async def list_pending_gap_flags(self) -> list[ResumeGapFlag]: ...


class CandidateProfileRepository(Protocol):
    async def get(self) -> CandidateProfile | None: ...
    async def save(self, profile: CandidateProfile) -> None: ...
